### ISSUE TITLE
Error (No such file or directory: 'aria2c': 'aria2c) while trying leech command

### ISSUE THREAD

**Issue by royal-cloud** [eldhomv/Gouttor#1]
09-Jul-22 03:55:51 - INFO - 😎THE BOT IS BOOTED AND READY TO USE--send /help for more🤖. [__init__.py:162]
09-Jul-22 03:55:51 - DEBUG - Using selector: EpollSelector [selector_events.py:54]
09-Jul-22 03:57:09 - INFO - None [extract_link_from_message.py:95]
09-Jul-22 03:57:09 - INFO - /home/azureuser/torrentleech-gdrive/tobrot/downloads/DODIIDMRVLEMP.torrent [incoming_message_fn.py:72]
09-Jul-22 03:57:09 - INFO - None [incoming_message_fn.py:73]
09-Jul-22 03:57:10 - INFO - ['aria2c', '--conf-path=/app/tobrot/aria2/aria2.conf', '--allow-overwrite=true', '--daemon=true', '--enable-rpc', '--disk-cache=0', '--follow-torrent=mem', '--max-connection-per-server=16', '--min-split-size=10M', '--rpc-listen-all=false', '--rpc-listen-port=6800', '--rpc-max-request-size=1024M', '--seed-ratio=0.01', '--seed-time=1', '--max-overall-upload-limit=2M', '--split=16', '--bt-stop-timeout=600'] [download_aria_p_n.py:68]
09-Jul-22 03:57:10 - ERROR - [Errno 2] No such file or directory: 'aria2c': 'aria2c' [dispatcher.py:235]
Traceback (most recent call last):
  File "/home/azureuser/torrentleech-gdrive/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/azureuser/torrentleech-gdrive/tobrot/plugins/incoming_message_fn.py", line 101, in incoming_message_f
    aria_i_p = await aria_start()
  File "/home/azureuser/torrentleech-gdrive/tobrot/helper_funcs/download_aria_p_n.py", line 73, in aria_start
    stderr=asyncio.subprocess.PIPE,
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'aria2c': 'aria2c'

**Comment by eldhomv** [comment]
Development was stopped by the developer and the codes are outdated. Please choose another repo.
